name: Build Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme myst-parser sphinx-copybutton
        pip install -r requirements.txt
        
    - name: Create documentation structure
      run: |
        mkdir -p docs_source
        mkdir -p docs_source/_static
        mkdir -p docs_source/_templates
        
    - name: Generate Sphinx configuration
      run: |
        cat > docs_source/conf.py << 'EOF'
        import os
        import sys
        sys.path.insert(0, os.path.abspath('..'))

        project = 'Cryogenic Cooling Time Calculator'
        copyright = '2025, Ming Liu'
        author = 'Ming Liu'
        release = 'v1.1.0'

        extensions = [
            'sphinx.ext.autodoc',
            'sphinx.ext.viewcode',
            'sphinx.ext.napoleon',
            'myst_parser',
            'sphinx_copybutton',
        ]

        templates_path = ['_templates']
        exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

        html_theme = 'sphinx_rtd_theme'
        html_static_path = ['_static']
        html_title = 'Cryogenic Cooling Time Calculator Documentation'

        source_suffix = {
            '.rst': None,
            '.md': 'myst_parser',
        }
        EOF
        
    - name: Create main documentation files
      run: |
        cat > docs_source/index.rst << 'EOF'
        Cryogenic Cooling Time Calculator
        ==================================

        Welcome to the Cryogenic Cooling Time Calculator documentation!

        This is a professional tool for calculating cooling time of niobium samples in cryocooler systems.

        Features
        --------

        * Parameter-based calculations
        * Visualization analysis
        * Dual language support
        * System schematic diagrams
        * Multi-threaded calculations

        Installation
        ------------

        .. code-block:: bash

           git clone https://github.com/iuming/Cryogenic_Cooling_Time_Calculator.git
           cd Cryogenic_Cooling_Time_Calculator
           pip install -r requirements.txt
           python cooling_gui.py

        About
        -----

        :Author: Ming Liu
        :Email: ming-1018@foxmail.com
        :GitHub: https://github.com/iuming
        :License: MIT License
        EOF
        
    - name: Build documentation
      run: |
        cd docs_source
        sphinx-build -b html . _build/html
        
    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs_source/_build/html
