name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort

    - name: Check Python syntax
      run: |
        # 检查Python语法错误
        python -m py_compile cooling_gui.py
        python -m py_compile core/calculation_engine.py
        python -m py_compile utils/font_utils.py
        python -m py_compile utils/test_utils.py
        python -m py_compile scripts/simple_calculator.py
        python -m py_compile scripts/test_components.py

    - name: Run flake8 linting
      run: |
        # 基本的代码质量检查
        flake8 --select=E9,F63,F7,F82 --show-source --statistics .

    - name: Check import organization
      run: |
        # 检查导入语句的组织
        isort --check-only --diff . || echo "Import organization suggestions available"

    - name: Validate project structure
      run: |
        # 验证项目结构
        echo "Checking project structure..."
        
        required_files=(
          "cooling_gui.py"
          "requirements.txt"
          "README.md"
          "core/calculation_engine.py"
          "utils/font_utils.py"
          "scripts/simple_calculator.py"
          "docs/USAGE.md"
        )
        
        missing_files=()
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            missing_files+=("$file")
          fi
        done
        
        if [ ${#missing_files[@]} -eq 0 ]; then
          echo "✅ All required files present"
        else
          echo "❌ Missing files:"
          printf '%s\n' "${missing_files[@]}"
          exit 1
        fi
