name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Basic syntax check
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

    - name: File structure check
      run: |
        echo "✓ 检查项目结构..."
        test -f cooling_gui.py && echo "✓ 主GUI文件存在"
        test -f core/calculation_engine.py && echo "✓ 计算引擎存在"
        test -f requirements.txt && echo "✓ 依赖文件存在"
        test -f README.md && echo "✓ 说明文档存在"
        echo "✓ 项目结构检查完成"
        
        if [ ${#missing_files[@]} -eq 0 ]; then
          echo "✅ All required files present"
        else
          echo "❌ Missing files:"
          printf '%s\n' "${missing_files[@]}"
          exit 1
        fi
